change filename for scripts

diff --git a/scripts/LAST/50-misc b/scripts/LAST/50-misc
--- a/scripts/LAST/50-misc
+++ b/scripts/LAST/50-misc
@@ -62,7 +62,7 @@ fi
 if [ $FAI_ACTION = "install" ]; then
     lskernels=$(echo $target/boot/vmlinu*)
     if [ ! -f ${lskernels%% *} ]; then
-	echo "ERROR: No kernel was installed. Have a look at shell.log" >&2
+	echo "ERROR: No kernel was installed. Have a look at scripts.log" >&2
 	error=1
     fi
 fi
